wcコマンドを作成
omochiumaiumai/ruby-practices pull request #9
Opened 2022-05-27 08:42 UTC by omochiumaiumai

2022-06-02 03:06 UTC, u1tnk requested changes
処理自体はちゃんとできていますね 👍 
インスタンス変数を使ってしまったこともあって、処理の流れがつかみづらいのが一番改善して欲しいポイントです。

- 変数名と中身を一致させるようにすること
- 全体的な流れ(入力を処理する、計算する、綺麗に並べる、出力するなど)のまとまりが分かるように整理する

を意識できれば良くなると思います 💪

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +  open_files = @specified_file.map { |file| File.open(file, 'r') }
ここで三回open_filesを作る必要は無いと思います。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +  @specified_file = $stdin.to_a
だいぶ大きく変わってしまうので言いづらいのですが、オブジェクト指向を使わないときにインスタンス変数を使うのはやめた方が良いです。単なるグローバル変数になってしまって処理の流れを読み取るのが難しくなってしまうので。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +  @lines = @specified_file.count
pipeのときの処理は特別なものでは無く
- ファイル名が無しの
- ファイル一個のときの処理

とほぼ同じなので、もう少し共通化できると良いと思います。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +  @various_data = @lines.zip(@words, @byte_size, @specified_file)
various_dataだと何が入っているのか直感的に分からないので、どんな種類のデータなのか、どのような目的で作ったものなのか？などの観点から名前を付けてみてください。
また、一般的に data/infoなどはよく使われるのですが、具体的な情報量が少ないので絶対では無いですが、使わないように心がけた方が良い命名ができると思います。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +ljusted_files = if options.values.any? == true
ちょっと細かいですが、今回サポートしている c/w/l以外にもwcのオプションは存在しているので、オプションが全部無いときは全部出すというのは良くないと思いました。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +ljusted_files = if options.values.any? == true
ljusted_filesという名前になっていますが、入るデータは various_dataとカウント結果などが入っていてファイル名では無いので変数名がおかしいと思います。

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +if options.values.any? == false
まったく同じ処理なのでできれば共通化したいですね。以下のような方法があると思います。

- メソッドにまとめる
- 合計もまとめて配列に入れてしまって一回で処理できるようにする
-

2022-06-02 03:06 UTC, u1tnk commented on 06.wc/wc.rb
> +ljusted_files.map! do |array|
![image](https://user-images.githubusercontent.com/279240/171544160-51f031b1-1b41-47b5-a761-a080dfff3827.png)
現在の処理だとこのように ファイル名が綺麗に並ばないようです。
厳密に一致させる必要はありませんが、ファイル名部分を左揃えで並ぶようにするようお願いします 🙏

2022-06-02 11:28 UTC, omochiumaiumai commented
レビューありがとうございます！
ご指摘いただいた部分を改善して再提出いたします…！

2022-06-06 11:22 UTC, omochiumaiumai commented on 06.wc/wc.rb
> +ljusted_files = if options.values.any? == true
少し混乱しているので確認させてください。
実際のwcコマンドをオプション無しで実行すると全ての要素が出力されます。
今回の私が作ったif文ではオプションが全く入っていないパターンでは45行目のelseを通ってすべての要素を出力し、オプションが一つでも入っていれば上39行目を通って出力するようにしたかったのですが、この作り方が良くないということでしょうか？

2022-06-07 02:39 UTC, u1tnk commented on 06.wc/wc.rb
> +ljusted_files = if options.values.any? == true
はい、if文の条件が「オプションが全く入っていないパターン」がちょっと良くないです。
「ちょっと細かいですが」と付けている通りプラクティスの範囲内では問題無いので、修正必須というほどではありません。

ただ、実業務を考えるとオプションが増えるというのは予想される機能追加で、そのときに気づかないと確実にバグを産むので、こういう「現状では問題無いが、本質的では無い条件」が良くないのでコメントさせてもらいました。

では、どう修正するのが良いか？というと、逆にして、各種一行表示するオプションを先に判定して、その他の場合に全部表示するようにすればロジック的にもほぼ同等で他にオプション追加されても問題無いコードになると思います。

2022-06-07 04:50 UTC, omochiumaiumai commented on 06.wc/wc.rb
> +ljusted_files = if options.values.any? == true
> ただ、実業務を考えるとオプションが増えるというのは予想される機能追加で、そのときに気づかないと確実にバグを産むので、こういう「現状では問題無いが、本質的では無い条件」が良くないのでコメントさせてもらいました。

後にオプションを追加することになった際にバグを産みやすいのですね…確認できてよかったです！ご指摘ありがとうございます。

2022-06-10 15:02 UTC, u1tnk requested changes

2022-06-10 15:02 UTC, u1tnk commented on 06.wc/wc.rb
> +def options_select(values, options)
色々考えて分からなったようなので例を書くと以下とかどうでしょう？
単純にcaseを使う例あたりでも良いと思います。
ちなみにdeleteせずにここで返ってきた配列を `file_values`に代入するイメージです。
```
def options_select(values, options)
  return [values[2]] if options['c']
  return [values[1]] if options['w']
  return [values[0]] if options['l']

  values
end
```

ついでに書いておくと、引数に与えたものをメソッド内部で修正するのはあまり良くなくて、加工して返り値で返ってきたものを使った方が分かりやすいというのもあります。引数にあるものが変更されていると、呼び出し元でその引数が他で参照されていて、意図せずに不具合になったりするケースもありますので。

2022-06-10 15:02 UTC, u1tnk commented on 06.wc/wc.rb
> +def file_names_get
通常の語順としては get_file_namesになりますが、get_始まりは rubocopに怒られますからねー。file_namesだと変数と重複しちゃうし、fetchとかcorrectとかを最初に付けると良いかと思います。

2022-06-10 15:02 UTC, u1tnk commented on 06.wc/wc.rb
> +    [' ']
dummyとして空白の文字列にしてると思うのですが、そういう使い方をするときは nilにするか、nilだと支障あるなら 空文字(`''`)で良いと思います。

2022-06-10 15:02 UTC, u1tnk commented on 06.wc/wc.rb
> +def input_check
これも通常だと動詞が先で check_inputになりますね。
ただ、checkを使うときにありがちなのですが、「何をチェックするのか？」という事が分かりづらくなるので使うときは何をcheckするのか分かるような名前にしましょう。_

2022-06-10 15:02 UTC, u1tnk commented on 06.wc/wc.rb
> +  entered_files = input_check
```
  entered_files = input_check
  file_values = calculate_values(entered_files)
  file_names = file_names_get
```
を単にならべた状態だと使っているメソッドも含めてもちょっと理解が難しいです。
それぞれ

- entered_files ファイル内部の文字列
- file_values ファイルごとの計算結果
- file_names ファイル名の配列

と思いますので、中身が分かるような変数名を考えてみてください。
(file_namesは中身と名前があっていると思いますが、 enterd_filesとの違いがなんだろう？って思うので入れています)

このままの構造で名前を工夫しても良いですが、一案としては以下みたいな構造を作れば変数は一個減りますね。

```
{
  "file_name": "中身",
}
```

2022-06-18 12:30 UTC, omochiumaiumai commented on 06.wc/wc.rb
> +def options_select(values, options)
ありがとうございます！
ご教示頂いた例ですと、条件分岐が真の時点で戻り値が返ってしまい、オプションが複数指定された場合に対応できないようなのですがどうすればよろしいでしょうか？
(オプション指定がclだった場合でも、一番上の`return [values[2]] if options['c']`で真が判定された時点でメソッドの実行が終了してcの要素が入った配列のみが返ってきます)

2022-06-20 11:35 UTC, u1tnk commented on 06.wc/wc.rb
> +def options_select(values, options)
なるほどー。
すみません、c/w/lは排他だと思っておりました。実際wcコマンドで試しましたが二つ指定もできるんですね 🙏 

そうなると、以下あたりでしょうか。

```
def options_select(values, options)
  return valeus if !options['c'] && !options['w'] && !options['l']

  filtered_values = []
  filtered_values += [values[0] if options['l']
  filtered_values += [values[1] if options['w']
  filtered_values += [values[2] if options['c']

  filtered_values
end
```

また、上記でも対応できそうですが、順番が抜けてしまうと何番目が何の数値か分からなくなるので、以下のようにデータ構造も調整した方が分かりやすくなるとは思います。
変えると上記ロジックは使えなくなりますが、基本は一緒だと思います。

```
{
  character_count: xxx,
  word_count: xxx,
  line_count: xxx,
}
```

2022-06-20 11:40 UTC, u1tnk commented on 06.wc/wc.rb
> +def options_select(values, options)
いちばん指摘したかった内容としては  ` options.values.any? ` を使うと危険という事で、その意味では今の delete_atを使うロジックでも大丈夫ではあります。
また、別の良くない習慣として「引数を直接修正する」というのがあって、それを避けたサンプルを説明無く書いてしまったので、分かりづらかったかもしれません 🙏 

「引数を直接修正する」が何故良くないかと言うと、メソッドを使う側が意図せずその変数を使うと想定外になってしまうからですね。
なので、 delete_atを使うのであれば dupやcloneを使って引数から別の変数にコピーしてから編集して引数には影響無いようにすればOKです。

2022-06-20 12:10 UTC, u1tnk requested changes
変数名以前よりよくなっているんですが少し冗長になっているところを指摘しました。

2022-06-20 12:10 UTC, u1tnk commented on 06.wc/wc.rb
> +  options = ARGV.getopts('c', 'l', 'w')
以前の変数名より格段に読みやすくなってると思います 👍

2022-06-20 12:10 UTC, u1tnk commented on 06.wc/wc.rb
> +  filename_stored_array = collect_filename_stored_array
`filename_stored_array `は下記の理由から `filenames`もしくは `file_names`で良いと思います。

- 変数にはデータがstoreされているのは普通なので不要
- arrayはruby(rails)界隈では使わず、配列は複数形で表現します。

2022-06-20 12:10 UTC, u1tnk commented on 06.wc/wc.rb
> +  file_calculation_results = calculate_values(strings_in_files)
resultsなのはメソッドの戻り値を格納しているので不要と思います。
メソッド名と合わせて`file_calculated_values`か`calculated_values` で良いかと思います。

2022-06-21 07:50 UTC, omochiumaiumai commented
レビューありがとうございます！
+ 変数名の変更
+ options_selectメソッドを`options.values.any?`を使わない形のハッシュでの処理に変更
引数`values`に入ってきた配列を、データ構造が分かりやすいようにハッシュ`values_hash`に`character_count:` `word_count:` `line_count:`のキーで代入し、deleteメソッドでオプションに対応したキーの値を削除して戻り値に渡す形に変更
+ 上記に伴い出力のoutputメソッドもハッシュでの処理に変更

以上三点の変更をしました。ご確認お願いいたします！

2022-06-21 07:52 UTC, omochiumaiumai commented on 06.wc/wc.rb
> +def options_select(values, options)
> `return values if !options['c'] && !options['w'] && !options['l']`

オプションが全く入っていないパターンを条件にifではなく、処理を行わずそのまま戻り値に返せばよかったのですね…！

>「引数を直接修正する」が何故良くないかと言うと、メソッドを使う側が意図せずその変数を使うと想定外になってしまうからですね。

今度から引数で渡ってきたものは直接修正せず、メソッド内で一度別の変数に代入して加工するようにします。ご教示ありがとうございます！

2022-06-28 02:09 UTC, u1tnk requested changes
すみません、前回まとめてもっと分かりやすく指摘できていれば良かったのですがもう少し見直しをお願いします。

もう少し処理を分割しましょう。特にprepare_outputあたりが計算の途中で文字列操作が入ったりしていてちょっと読むのが難しいです。
使いやすいデータを揃える事に集中して先にやって、出力するときは文字列処理に集中するという感じです。

現状 prepare_outputが複雑になっていて outputはほぼ何もやってないので、outputで整形(ljustとかtotalの追加とか)するのが良いかなと思いました。

2022-06-28 02:09 UTC, u1tnk commented on 06.wc/sample/wc.rb
> +# frozen_string_literal: true
こちらは 参考として残してると思いますが、git辿れば確認できますし、 この `Files changed`にあると提出物と思って混乱しますのでcommitしないようお願いします 🙏

2022-06-28 02:09 UTC, u1tnk commented on 06.wc/wc.rb
> +  total_values = calculated_values.transpose
prepare_output に渡すために transposeしているようですが、prepare_output専用の変数であれば calculated_valuesも渡しているので prepare_output内で生成すれば良いと思います。

2022-06-28 02:09 UTC, u1tnk commented on 06.wc/wc.rb
> +  max_character = file_names.max.length
この名前だと 文字が入ってそうなので、 max_lengthとかが良いと思います。

2022-06-28 02:09 UTC, u1tnk commented on 06.wc/wc.rb
> +  total_values.insert(-1, ' ', 'total')
細かいですが、

`total_values += [' ', 'total'] `の方が直感的かなと思いました。

2022-06-28 02:09 UTC, u1tnk commented on 06.wc/wc.rb
> +  values_hash = { line_count: values[0], word_count: values[1], character_count: values[2] }
すみません、説明不足だったと思いますが、こういうhashにするのであれば calculate_values の時点でhash形式にしましょう。
「配列の1番目が文字数」よりも 「hashのcharacter_countが文字数」の方が分かりやすいので。

2022-06-28 07:03 UTC, omochiumaiumai commented on 06.wc/sample/wc.rb
> +# frozen_string_literal: true
提出用ではないファイルを間違えてコミットしていました…！
申し訳ございません、ご指摘ありがとうございます！

2022-07-01 14:38 UTC, omochiumaiumai commented
お疲れさまです！
+ 変数名の変更
+ prepare_outputメソッドから整形の処理をoutputメソッドに移す
以上を行いました。レビューをお願いいたします。

2022-07-02 15:05 UTC, u1tnk requested changes
だいぶ整理されましたね！ もうちょっとです 💪

2022-07-02 15:05 UTC, u1tnk commented on 06.wc/wc.rb
> +  total_values = calculated_values.values.map(&:sum)
いったん変数に入れて次に他の変数に入れているだけなのでこの行は不要です。
以下で大丈夫です。変数の名前考えるの大変なのでラクしていきましょう 💪 
```
calculated_values[:total_values] = calculated_values.values.map(&:sum)
```

2022-07-02 15:05 UTC, u1tnk commented on 06.wc/wc.rb
> +def prepare_output(calculated_values, options)
結果として、二つメソッド呼び出して変数に入れてるだけなので、無くても良くなりましたね…
見た目よりフォーマット系の処理が多かったんですね。
無しにしましょう！

2022-07-02 15:05 UTC, u1tnk commented on 06.wc/wc.rb
> +  output = processed_values.transpose.map do |array|
ここも変数に入れて次の行で使ってるだけなので無しで。
というか ouputメソッド内でoutput変数を使うのは動きますが業務的にNGというのもあります。

単純に

```
puts processed_values.transpose.map do |array|
    array.insert(-2, ' ')
    array.join
  end
```
で大丈夫です 🙆‍♀️

2022-07-02 15:05 UTC, u1tnk commented on 06.wc/wc.rb
> +  puts total_values.join if output.count > 1
結局のところ `output.count > 1` のときしか total_valuesは使わないので、上でいったん整理しているようですが、ここでやれば良いですね。
prepare_outputは消すので、ここで作れば良いです。
今の処理を使って整理すると以下となります。

```
puts (calculated_values.values.map(&:sum) + [' ', 'total']).join if output.count > 1
```

なのですが、配列に固定値入れてjoinはちょっと分かりづらいので以下の方がオススメです。

```
puts "#{calculated_values.values.map(&:sum).join} total " if output.count > 1
```

2022-07-06 02:55 UTC, u1tnk requested changes
すみません、hashを使うように指摘したときの指示が具体的で無かったので混乱させてしまったようです 🙏 
また、質問に対して局所的な回答に留めてしまった事で部分的には改善しても全体として混乱が残ってしまったのだと思います。

出力のところで辻褄を合わせる事もできなくは無いですが、だいぶ無理が来ていて、この後オブジェクト指向版ではもっとブラッシュアップをしなければならず、このプラクティスだけ通しても後で混乱すると思ったので改善をお願いします。

全体の流れをまず、以下のようなデータを作る事を目的としてください。
これだけあれば情報量は足りています。(stdinのときはfile_nameは空白にすると良いと思います)
オプションはここまでは意識して分離する必要は無いですが参照できるように保存はしておいてください。

```
[
{file_name: "hoge.txt", word_count: 10, line_count: 3, character_count: 20},
{file_name: "fuga.txt", word_count: 15, line_count: 5, character_count: 30},
]
```

で、ここまでくればあとはオプションごとに

```
records.each do |r|
  if options['c']
  p "#{r[:character_count].to_s.rjust(8, ' ')} #{r[:file_name].ljust(max_length, '0')}"
end
# 2ファイル以上あったらtotalの計算、表示
elsif # 他のオプション処理
省略
end
```

という風にすれば途中でファーマット関係の破壊的変更をする事なく処理できます。

2022-07-06 02:55 UTC, u1tnk commented on 06.wc/wc.rb
> +def output(values_and_total_values)
values_and_total_values は変更の結果今は total_valueは入っていないので変数名の変更をお願いします。

2022-07-06 02:55 UTC, u1tnk commented on 06.wc/wc.rb
> +    puts array.join
基本的にここでフォーマットさせながら出力すればこれ以前に破壊的な変更をする必要は無いです。
イメージ的には以下のような感じです。

```
p "#{r[:character_count].to_s.rjust(8, ' ')} 省略 #{r[:file_name].ljust(max_length, '0')}"
```

として欲しいのですが、データ構造がこうできるようにはなっていないようです。
データ構造については全体になってくるので、別途書きます。

2022-07-06 07:08 UTC, omochiumaiumai commented
お疲れさまです！

> すみません、hashを使うように指摘したときの指示が具体的で無かったので混乱させてしまったようです 🙏
> また、質問に対して局所的な回答に留めてしまった事で部分的には改善しても全体として混乱が残ってしまったのだと思います。
> 出力のところで辻褄を合わせる事もできなくは無いですが、だいぶ無理が来ていて、この後オブジェクト指向版ではもっとブラッシュアップをしなければならず、このプラクティスだけ通しても後で混乱すると思ったので改善をお願いします。

上手く意図を汲み取れずすみません💦いつもレビューありがとうございます！
後々困ると思うので、整然としたコードにできるように頑張りたいです💪

---
まずご指摘いただいた
+ 変数名の変更
+ 配列の中にデータを揃えたハッシュを作る
+ 条件に合わせて出力

以上の点を改善したのですが、二点ほど気になることがあるので質問させてください。

①複数オプションへの対応
先日プラクティスの終了条件が改定され、複数オプションへの対応が必須化されました。https://bootcamp.fjord.jp/announcements/694
今回改善した出力方法ですと、複数オプションを組み合わせた場合に対応できないと思いますが、このまま進めてもよろしいでしょうか？(すでに提出済みの場合はレビュー担当のメンターに確認するようにとのことです)

②rubocopの警告convention:Metrics/PerceivedComplexity)
<img width="779" alt="image" src="https://user-images.githubusercontent.com/88243294/177483619-37f5ff00-658e-4160-90c1-f96f77cbc9ab.png">
`calculate_values`メソッドと`output`メソッドについてrubocopに怒られてしまいました。
恐らくですが代入や、または繰り返し処理やif文が複雑(多すぎる)ことで怒られているため、新たにメソッドを切り出すか簡略化の必要がありそうです。
どのように対応すればよいか悩んでいます〜よろしければご教示お願いいたします。

2022-07-06 08:07 UTC, u1tnk requested changes
対応早い！
思い切って全体整理お願いして良かったです 👍 

前のバージョンより格段に良くなっていますが、コメントもしている見てみてください。

オプションに対応していない点は個別にコメントしています。

rubocopで指摘される点は、今回の処理整理をした後でも出るようならメソッドを切り出しましょう。
total関連の処理とか、指摘した各項目(l/w/c)の出力判定をするあたりが切り出しやすいかなと思います。

2022-07-06 08:07 UTC, u1tnk commented on 06.wc/wc.rb
> +    ARGV.map { |file| File.open(file, 'r').readlines }
ここでファイル名は取れているので、戻り値を「ファイルの中身の配列」から

stdinのとき
```
[{ file_name: '', content: #{渡された文字列} }]
```

ファイル名のとき

```
[{ file_name: 'file1.txt', content: #{読みとった文字列}}, .....]
```

にすれば collect_file_namesが不要になります。

2022-07-06 08:07 UTC, u1tnk commented on 06.wc/wc.rb
> +def calculate_values(strings_in_files)
ここもまだ内部で破壊的変形をするような処理があるのと、それぞれの配列を zipしているあたりがちょっと分かりづらいです。

check_input_source の内容を変えると以下のようにできます。

```
# 仮に filesという配列名とします。良い名前は考えてください。
files.map do |file|
  file_count = # file[:content]を利用して計算
  ...略
  { file_name: file_count, line_count: line_count, word_count: word_count, character_count: character_count }
end
```

2022-07-06 08:07 UTC, u1tnk commented on 06.wc/wc.rb
> +# def options_select(values_hash, options)
いったんコメントアウトするのは良いですが、コミットするときには消しましょう。

2022-07-06 08:07 UTC, u1tnk commented on 06.wc/wc.rb
> +  values.each do |values_hash|
確かにおっしゃる通り複数オプションに対応できていませんね！失礼しました 🙏 

方針を書くのでやってみてください。

- 最初に l/w/cそれぞれを出力するかをoption状況から判定して変数に入れておく。
- l/w/cの順番は決まっているので、それぞれ上の変数を使ってを pでは無く putsで出力する
    - 一行中の部品を分けて出力を判定するイメージ

2022-07-06 08:07 UTC, u1tnk commented on 06.wc/wc.rb
> +  max_length = file_names.max.length
collect_file_namesが無くなりますが、 新しいデータでもfile_nameはあるので問題無いです。
テクニックなので書いてしまうと以下のようにするだけです。 `_1`あたりは最近のrubyで書けるようになった書き方なので覚えておいてください。

`values.map{_1[:file_name].length}.max`

2022-07-10 12:10 UTC, omochiumaiumai commented on 06.wc/wc.rb
> +  values.each do |values_hash|
お疲れさまです。
> 最初に l/w/cそれぞれを出力するかをoption状況から判定して変数に入れておく。
> l/w/cの順番は決まっているので、それぞれ上の変数を使ってを pでは無く putsで出力する

まず`options`からtrueかfalseの判定を取得した変数(`line_judge,word_judge,character_judge`のような)を作り、outputメソッドの最後でファイル数分putsするループを書く感じでしょうか？
```
# 例
# ファイル数分ループする
file_count.each do |count|
  puts  "#{values_hash[:line_count][count] if line_judge}#{values_hash[:word_count][count] if word_judge}#{values_hash[:character_count][0] if character_judge}" 
end
```

2022-07-10 13:23 UTC, u1tnk commented on 06.wc/wc.rb
> +  values.each do |values_hash|
はい、ロジック的にはそういう意図です。
…が、失礼しました。 putsと printを混同していました。 putsだと改行出力されちゃうんで printの方ですね 🙏 

また、上記だと一行が長くて見づらいので

```
file_count.each do |count|
  print values_hash[:line_count][count] if line_judge
  print values_hash[:word_count][count] if word_judge
  print values_hash[:character_count][0] if character_judge
  ...
  puts "" 
end
```

のようにすると見やすくなると思います。

2022-07-11 09:05 UTC, omochiumaiumai commented
お疲れさまです！レビューありがとうございます！
ご指摘いただいた点を改善いたしましたので、ご確認をお願いいたします。


rubocopに指摘されたoutputメソッドの問題(convention:Metrics/PerceivedComplexity)が解決できなかったため、お力添えいただけますと幸いです。
以下のようにoutputメソッドからトータルの出力処理部分の切り出しを試しましたが、オプションの条件分岐が複雑なのか切り出したメソッドの方も引っかかってしまいました

```ruby
def output(values_and_filenames, options)
  values_and_filenames = values_and_filenames[0]
  file_count = values_and_filenames[:file_names].count
  max_length = values_and_filenames[:file_names].map { _1.length }.max
  file_count.times do |count|
    print values_and_filenames[:line_count][count].to_s.rjust(8) if options['l']
    print values_and_filenames[:word_count][count].to_s.rjust(8) if options['w']
    print values_and_filenames[:character_count][count].to_s.rjust(8) if options['c']
    print values_and_filenames[:file_names][count].ljust(max_length)

    puts ''
  end
end

def total_output(values_and_filenames, options)
  values_and_filenames = values_and_filenames[0]
  file_count = values_and_filenames[:file_names].count
  max_length = values_and_filenames[:file_names].map { _1.length }.max

  print values_and_filenames[:line_count].sum.to_s.rjust(8) if options['l'] && file_count
  print values_and_filenames[:word_count].sum.to_s.rjust(8) if options['w'] && file_count
  print values_and_filenames[:character_count].sum.to_s.rjust(8) if options['c'] && file_count
  print ' total'.ljust(max_length) if file_count
end
# Perceived complexity for total_output is too high. [9/8] 
```

2022-07-12 01:39 UTC, u1tnk commented
以下のように切り出しをoutputの一機能として、outputから呼び出せば共通部分が消せるので大丈夫でした。

```
def output(values_and_filenames, options)
  values_and_filenames = values_and_filenames[0]
  max_length = values_and_filenames[:file_names].map { _1.length }.max
  file_count = values_and_filenames[:file_names].count

  file_count.times do |count|
    print values_and_filenames[:line_count][count].to_s.rjust(8) if options['l']
    print values_and_filenames[:word_count][count].to_s.rjust(8) if options['w']
    print values_and_filenames[:character_count][count].to_s.rjust(8) if options['c']
    print values_and_filenames[:file_names][count].ljust(max_length)

    puts ''
  end

  output_total if file_count > 1
end

def output_total(values_and_filenames, options)
  print values_and_filenames[:line_count].sum.to_s.rjust(8) if options['l']
  print values_and_filenames[:word_count].sum.to_s.rjust(8) if options['w']
  print values_and_filenames[:character_count].sum.to_s.rjust(8) if options['c']
  print ' total'.ljust(max_length)
end
```

また、変更は不要ですが、以前伝えたデータ構造がちょっと違う事に気づいたので指摘しておきます。

私は以下のようにして欲しかったのですが、

```
 [
  {:file_name=>" hoge.txt", :line_count=>62, :word_count=>163, :character_count=>2025},
  {:file_name=>" fuga.txt", :line_count=>82, :word_count=>195, :character_count=>3001},
]
```

現状は以下のようになっています。

```
 [{:file_names=>[" hoge.txt", " fuga.txt"], :line_count=>[62, 82], :word_count=>[163, 195], :character_count=>[2025, 3001]}]
```

上記処理の

```
file_count = values_and_filenames[:file_names].count
file_count.times do |count|
  print values_and_filenames[:line_count][count].to_s.rjust(8) if options['l']
  # 略 
end
```

のところは上のデータ構造なら

```
values_and_filenames.each |value_and_filename|
  print values_and_filename[:line_count].to_s.rjust(8) if options['l']
# 略
end
```

となり、かなりシンプルになります。
とはいえ影響大きいのでこのままにして、wcのobject版の宿題でも大丈夫です 🙆‍♀️ (object版だと上のような構造にはなりますがhashじゃなくてobjectになるので注意です)

2022-07-12 01:41 UTC, u1tnk requested changes
ご質問頂いたところは別途回答しました。

あと、前のコメントに考慮しているようなものもあったので途中なのかもしれませんが optionsの処理が変わっており、 オプションを何もつけないと何も出力されないようになってしまっているのでご対応お願いします。

2022-07-13 06:34 UTC, omochiumaiumai commented
レビューありがとうございます！
> また、変更は不要ですが、以前伝えたデータ構造がちょっと違う事に気づいたので指摘しておきます。

すみません、次回wcオブジェクト版で変更したいと思います！
> あと、前のコメントに考慮しているようなものもあったので途中なのかもしれませんが optionsの処理が変わっており、 オプションを何もつけないと何も出力されないようになってしまっているのでご対応お願いします。

ご指摘ありがとうございます！
条件分岐が増えた分またrubocopに怒られてしまったのですが、どのように解決すればよろしいでしょうか？
以下の二通りを試しましたが、どちらも引っかかりました。
```ruby
if !options['c'] && !options['w'] && !options['l']
    file_count.times do |count|
      print values_and_filenames[:line_count][count].to_s.rjust(8)
      print values_and_filenames[:word_count][count].to_s.rjust(8)
      print values_and_filenames[:character_count][count].to_s.rjust(8)
      print values_and_filenames[:file_names][count].ljust(max_length)
      puts ''
    end
  else
    file_count.times do |count|
      print values_and_filenames[:line_count][count].to_s.rjust(8) if options['l']
      print values_and_filenames[:word_count][count].to_s.rjust(8) if options['w']
      print values_and_filenames[:character_count][count].to_s.rjust(8) if options['c']
      print values_and_filenames[:file_names][count].ljust(max_length)
      puts ''
    end
  end
# Method has too many lines. [21/20] (convention:Metrics/MethodLength)
# Perceived complexity for output is too high. [10/8] (convention:Metrics/PerceivedComplexity)
```
```ruby
file_count.times do |count|
    print values_and_filenames[:line_count][count].to_s.rjust(8) if options['l'] || !options['c'] && !options['w'] && !options['l']
    print values_and_filenames[:word_count][count].to_s.rjust(8) if options['w'] || !options['c'] && !options['w'] && !options['l']
    print values_and_filenames[:character_count][count].to_s.rjust(8) if options['c'] || !options['c'] && !options['w'] && !options['l']
    print values_and_filenames[:file_names][count].ljust(max_length)
    puts ''
  end
# Perceived complexity for output is too high. [15/8] (convention:Metrics/PerceivedComplexity)
```

2022-07-13 12:19 UTC, u1tnk commented
> 条件分岐が増えた分またrubocopに怒られてしまったのですが、どのように解決すればよろしいでしょうか？

まずは前に触れましたが line_judge みたいなフラグを作るようにして別のメソッドに切り出すが良いと思います。

```
def display_line?(options)
   (!options['c'] && !options['w'] && !options['l']) || options['l']
end

display_line = display_line?(options)
# 上の利用して出力表示をする
```

これでどうでしょうか？

2022-07-13 13:06 UTC, omochiumaiumai commented
> まずは前に触れましたが line_judge みたいなフラグを作るようにして別のメソッドに切り出すが良いと思います。

ありがとうございます！複雑度がかなり減りました！
`Perceived complexity for output is too high. [9/8] `ともう一段階減らす必要があったので
```ruby
def main
  options = ARGV.getopts('c', 'l', 'w')
  filename_and_contents = check_input_source
  values_and_filenames  = calculate_values(filename_and_contents)
  output(values_and_filenames, options)
  output_total(values_and_filenames, options) if values_and_filenames[0][:file_names].count > 1
end
```
outputメソッド内のoutput_totalメソッドをmainメソッドで動かす形に変更しました。ご確認よろしくお願いいたします。

2022-07-13 13:20 UTC, u1tnk requested changes

2022-07-13 13:20 UTC, u1tnk commented on 06.wc/wc.rb
> +  values_and_filenames = values_and_filenames[0]
ここらへんが outputと重複しています。
以前私がサンプルを書いたように outputメソッドから呼び出すようにすれば重複が無くせますのでお試しください。

2022-07-13 13:20 UTC, u1tnk commented on 06.wc/wc.rb
> +def display_line?(options)
私が書いたサンプルは 

````
def display_line?(options)
   (!options['c'] && !options['w'] && !options['l']) || options['l']
end 
```

にしました、同様な `display_word?`/`display_character?`があれば表示するときは  

```
... if  options['l'] || display_line
```
では無く

```
... if display_line
```

だけで済むような意図でしたので、対応お願いします。

2022-07-13 13:39 UTC, omochiumaiumai commented
ご確認ありがとうございます！意図を掴めずすみません。
各オプションごとにメソッドを切り出して、メインに移したoutput_totalメソッドをoutputメソッドに戻しました。
ご確認お願いいたします。

2022-07-13 13:56 UTC, u1tnk approved these changes

2022-10-29 03:49 UTC, merged